"""init

Revision ID: c9bb26f7a23b
Revises: 
Create Date: 2026-07-16 19:25:59.538087
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c9bb26f7a23b'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('source', sa.Enum('reddit', 'x', 'github_issues', 'github_discussions', 'hackernews', 'stackoverflow', 'discord', 'producthunt', name='source'), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_authors_source'))
    )
    op.create_table('companies',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug'))
    )
    op.create_table('graph_nodes',
    sa.Column('kind', sa.Enum('problem', 'industry', 'product', 'company', 'author', 'technology', 'feature', 'pain_point', 'trend', 'topic', name='node_kind'), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes')),
    sa.UniqueConstraint('kind', 'key', name=op.f('uq_graph_nodes_kind'))
    )
    op.create_index('ix_graph_nodes_kind', 'graph_nodes', ['kind'], unique=False)
    op.create_table('industries',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['industries.id'], name=op.f('fk_industries_parent_id_industries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries')),
    sa.UniqueConstraint('slug', name=op.f('uq_industries_slug'))
    )
    op.create_table('source_cursors',
    sa.Column('source', sa.Enum('reddit', 'x', 'github_issues', 'github_discussions', 'hackernews', 'stackoverflow', 'discord', 'producthunt', name='source'), nullable=False),
    sa.Column('stream', sa.Text(), nullable=False),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_cursors')),
    sa.UniqueConstraint('source', 'stream', name=op.f('uq_source_cursors_source'))
    )
    op.create_table('technologies',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technologies')),
    sa.UniqueConstraint('slug', name=op.f('uq_technologies_slug'))
    )
    op.create_table('topics',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('slug', name=op.f('uq_topics_slug'))
    )
    op.create_table('trend_snapshots',
    sa.Column('subject_type', sa.Enum('topic', 'industry', 'pain_cluster', 'technology', name='trend_subject'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.Column('avg_severity', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_snapshots')),
    sa.UniqueConstraint('subject_type', 'subject_id', 'window_start', name=op.f('uq_trend_snapshots_subject_type'))
    )
    op.create_index('ix_trend_snapshots_subject', 'trend_snapshots', ['subject_type', 'subject_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('src_id', sa.UUID(), nullable=False),
    sa.Column('dst_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Enum('experiences', 'belongs_to', 'competes_with', 'mentions', 'requests', 'solves', 'built_with', 'trending_in', 'complains_about', name='edge_relation'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_dst_id_graph_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_id'], ['graph_nodes.id'], name=op.f('fk_graph_edges_src_id_graph_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges')),
    sa.UniqueConstraint('src_id', 'dst_id', 'relation', name=op.f('uq_graph_edges_src_id'))
    )
    op.create_index('ix_graph_edges_dst_id', 'graph_edges', ['dst_id'], unique=False)
    op.create_index('ix_graph_edges_src_id', 'graph_edges', ['src_id'], unique=False)
    op.create_table('pain_clusters',
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('canonical_statement', sa.Text(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('avg_severity', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_pain_clusters_industry_id_industries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pain_clusters'))
    )
    op.create_table('posts',
    sa.Column('source', sa.Enum('reddit', 'x', 'github_issues', 'github_discussions', 'hackernews', 'stackoverflow', 'discord', 'producthunt', name='source'), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('community', sa.Text(), nullable=True),
    sa.Column('thread_external_id', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('has_pain_signal', sa.Boolean(), nullable=True),
    sa.Column('enrichment_status', sa.Enum('pending', 'gated', 'enriched', 'failed', name='enrichment_status'), nullable=False),
    sa.Column('pipeline_version', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_posts_author_id_authors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_posts_source'))
    )
    op.create_index('ix_posts_content_hash', 'posts', ['content_hash'], unique=False)
    op.create_index('ix_posts_enrichment_status', 'posts', ['enrichment_status'], unique=False)
    op.create_index('ix_posts_posted_at', 'posts', ['posted_at'], unique=False)
    op.create_index('ix_posts_search_vector', 'posts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('products',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_products_company_id_companies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_table('comments',
    sa.Column('source', sa.Enum('reddit', 'x', 'github_issues', 'github_discussions', 'hackernews', 'stackoverflow', 'discord', 'producthunt', name='source'), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('parent_external_id', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_comments_author_id_authors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_comments_source'))
    )
    op.create_index('ix_comments_post_id', 'comments', ['post_id'], unique=False)
    op.create_table('enrichments',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('pipeline_version', sa.Integer(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_enrichments_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrichments')),
    sa.UniqueConstraint('post_id', 'stage', 'pipeline_version', name=op.f('uq_enrichments_post_id'))
    )
    op.create_index('ix_enrichments_stage', 'enrichments', ['stage'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('company', 'product', 'person', 'technology', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('surface_text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('context_quote', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_entity_mentions_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_mentions'))
    )
    op.create_index('ix_entity_mentions_entity', 'entity_mentions', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_entity_mentions_post_id', 'entity_mentions', ['post_id'], unique=False)
    op.create_table('feature_requests',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_feature_requests_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_feature_requests_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_requests'))
    )
    op.create_index('ix_feature_requests_post_id', 'feature_requests', ['post_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('suggested_solution', sa.Text(), nullable=True),
    sa.Column('pain_cluster_id', sa.UUID(), nullable=True),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'active', 'archived', name='opportunity_status'), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('generated_by_model', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_opportunities_industry_id_industries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pain_cluster_id'], ['pain_clusters.id'], name=op.f('fk_opportunities_pain_cluster_id_pain_clusters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('slug', name=op.f('uq_opportunities_slug'))
    )
    op.create_index('ix_opportunities_composite_score', 'opportunities', ['composite_score'], unique=False)
    op.create_index('ix_opportunities_status', 'opportunities', ['status'], unique=False)
    op.create_table('post_industries',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_post_industries_industry_id_industries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_industries_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'industry_id', name=op.f('pk_post_industries')),
    sa.UniqueConstraint('post_id', 'industry_id', name=op.f('uq_post_industries_post_id'))
    )
    op.create_index('ix_post_industries_industry_id', 'post_industries', ['industry_id'], unique=False)
    op.create_table('post_topics',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_topics_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_post_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'topic_id', name=op.f('pk_post_topics')),
    sa.UniqueConstraint('post_id', 'topic_id', name=op.f('uq_post_topics_post_id'))
    )
    op.create_index('ix_post_topics_topic_id', 'post_topics', ['topic_id'], unique=False)
    op.create_table('problems',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('current_workaround', sa.Text(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('pain_cluster_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pain_cluster_id'], ['pain_clusters.id'], name=op.f('fk_problems_pain_cluster_id_pain_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_problems_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    op.create_index('ix_problems_pain_cluster_id', 'problems', ['pain_cluster_id'], unique=False)
    op.create_index('ix_problems_post_id', 'problems', ['post_id'], unique=False)
    op.create_table('opportunity_reports',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_reports_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_reports'))
    )
    op.create_table('opportunity_scores',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('pain', 'trend', 'opportunity', 'competition', 'novelty', 'revenue_potential', 'virality_potential', 'market_size', 'confidence', name='score_kind'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_scores_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_scores')),
    sa.UniqueConstraint('opportunity_id', 'kind', name=op.f('uq_opportunity_scores_opportunity_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_scores')
    op.drop_table('opportunity_reports')
    op.drop_index('ix_problems_post_id', table_name='problems')
    op.drop_index('ix_problems_pain_cluster_id', table_name='problems')
    op.drop_table('problems')
    op.drop_index('ix_post_topics_topic_id', table_name='post_topics')
    op.drop_table('post_topics')
    op.drop_index('ix_post_industries_industry_id', table_name='post_industries')
    op.drop_table('post_industries')
    op.drop_index('ix_opportunities_status', table_name='opportunities')
    op.drop_index('ix_opportunities_composite_score', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_feature_requests_post_id', table_name='feature_requests')
    op.drop_table('feature_requests')
    op.drop_index('ix_entity_mentions_post_id', table_name='entity_mentions')
    op.drop_index('ix_entity_mentions_entity', table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index('ix_enrichments_stage', table_name='enrichments')
    op.drop_table('enrichments')
    op.drop_index('ix_comments_post_id', table_name='comments')
    op.drop_table('comments')
    op.drop_table('products')
    op.drop_index('ix_posts_search_vector', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_posted_at', table_name='posts')
    op.drop_index('ix_posts_enrichment_status', table_name='posts')
    op.drop_index('ix_posts_content_hash', table_name='posts')
    op.drop_table('posts')
    op.drop_table('pain_clusters')
    op.drop_index('ix_graph_edges_src_id', table_name='graph_edges')
    op.drop_index('ix_graph_edges_dst_id', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('ix_trend_snapshots_subject', table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_table('topics')
    op.drop_table('technologies')
    op.drop_table('source_cursors')
    op.drop_table('industries')
    op.drop_index('ix_graph_nodes_kind', table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_table('companies')
    op.drop_table('authors')
    # ### end Alembic commands ###
